import type { Metadata } from 'next';
import './globals.css';
import { Roboto_Mono } from 'next/font/google';
import React from 'react';
import { Providers } from '@/components/providers/providers';
import { Sidebar } from '@/components/ui/sidebar';
import { TopMenu } from '@/components/ui/TopMenu';

const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-roboto-mono',
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoMono.className} antialiased`}>
        <Providers>
          <TopMenu />
          <Sidebar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
